### PR TITLE
Process Capability Interface Draft

### PR DESCRIPTION
**Pull request by milenasophie**

### CODE REVIEW

**Comment by vandenman** [comment]
you commited a file called `processCapability.qml.autosave`. Did you mean to commit `processCapability.qml`?

**Comment by milenasophie** [comment]
Yes! Sorry I will try to change it when I’m on my laptop.

**Review by vandenman — CHANGES_REQUESTED** [review]
The changes here look fine!

However, could you try to adhere to the [QML style guide](https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/development/jasp-qml-style-example.qml)?

Also, I'd recommend you to use Qt Creator to edit QML files (in case you didn't do so already). If you use Qt Creator, [here's a link that explains how to change the default indent from spaces to tabs](https://doc.qt.io/qtcreator/creator-indenting-code.html#indenting-qml-files).

Also, to delete `inst/qml/processCapability.qml.autosave`, navigate to `inst/qml/` in the finder and delete the file called `processCapability.qml.autosave`.

**Comment by milenasophie** [comment]
I just added the changes according to the guide. I was editing in QT creator but I had the wrong default indent indeed. I hope the style is right now :)

**Pull request merged**
