### PR TITLE
Input Validation

### PR DESCRIPTION
**Pull request by JTPetter**
https://github.com/jasp-stats/jaspProcessControl/issues/64

### CODE REVIEW

**Comment by vandenman** [comment]
If I open type 1 Gauge I immediately get this error:

image

This does not fix Gauge r&R or the other analyses? Could you let me know:
1. when you're finished.
2. What is and isn't fixed. It's fine if you don't fix everything on such short notice, but then I know what to look at.

**Comment by JTPetter** [comment]
Yes, I am still working on it! I'll make a more informative PR next time

**Comment by JTPetter** [comment]
Ok, that should address almost all of the bugs you mentioned. 

Regarding Attribute Agreement Analysis: 
1) The problem here is that the standards column has different factor levels than the measurement column. I'll need some more time to create a sensible error message for this. 
2) No, scale should not be allowed in measurements. I changed the name to appraisal.

General: 
There are issues with all analyses that use a t-test when the input only has 1 value (e.g. missing99). I will need some more time to find a way around this.

**Comment by koenderks** [comment]
Seems like you can just not run the t test in case of < 2 values?

**Review by koenderks — APPROVED** [review]

**Pull request merged**
